### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by CVUsers** [OpenNLPLab/AVSBench#1]
我下载了您的数据，但只看到12971张Mask图，没有videos，没有语音，这如何训练？这是正常的吗？麻烦发送一份完整能训练的数据，纵使给一小部分，也可以，感谢：2665312447@qq.com

**Comment by CVUsers** [comment]
I downloaded your data, but I only saw 12971 mask images, no videos, no voice. How to train? Is this normal? Please send a complete training data, even if it is given to a small part. Thank you，2665312447@qq.com

**Comment by jasongief** [comment]
Thanks for your interest. As stated in the README, you are suggested to request the whole data by email. I have sent the data to your email and hope that can help you.

**Comment by CVUsers** [comment]
Thank you.栓Q~ Your segmentation effect doesn't look very good (but the sound source localization looks good). I will do some help next

**Comment by jasongief** [comment]
I am not quite clear about the performance comparison you said. But you can definitely get some inspiration from the sound source localization methods. Hope to see your nice work soon.

**Comment by Devin-Pi** [comment]
Hi, Jasongief!

Firstly, thanks for sharing your work!

Because I want to follow your work. So, could you please share the dataset with me?  My email address is rendong.pi@outlook.com.

Actually, I have sent an email to you for the processed audios and videos. But I have not got feedback until now. So, I contacted you here.

Looking forward to your reply!

**Comment by jasongief** [comment]
@RendongPi Hi, I did not receive your email for some reason. I have just sent the AVSBench data to your email, please check that.

**Comment by Devin-Pi** [comment]
@jasongief I have received your email. Thanks for your reply, again!
