### ISSUE TITLE
Some questions for your setting

### ISSUE THREAD

**Issue by yyliu01** [OpenNLPLab/AVSBench#13]
**Thanks so much for sharing such amazing datasets!**  @jasongief  @OpenNLPLab123 
We are trying to follow your work and have some questions about the setting,

1). In the segmentation, the previous datasets don't change the resolution ratio because:
  1. force the image into one size (i.e., 224, in your case)  will destroy the semantic meaning of the input data, and 
  2. it will also reduce your project's practicability in real-life challenges, as your pixel-wise classifier is trained in different domains.

For example, [Pascal VOC12](http://host.robots.ox.ac.uk/pascal/VOC/) and [Cityscapes](https://www.cityscapes-dataset.com/) both provide the images and masks in vanilla resolution. I'm wondering whether you can provide them in the original size (like in the VGG Sound) as an additional sources.

2). The traditional segmentation task is for multi-class pixel-wise classification. However, your measurement is based on the binary label, which is more like salient object detection or foreground segmentation. Please give us some advice.

Best regards,
Yuyuan Liu

**Comment by jasongief** [comment]
@yyliu01 Hi Yuyuan, thanks for your question, I appreciate your valuable advice. 

1). It would be better to provide the frames and masks with the original resolution. We will release that as soon as possible.

2). You are right. Since the proposed AVS task does not use the category label of sounding objects, the outputs are represented by binary maps indicating which pixels correspond to the audio. We are trying to upgrade the AVSBench data with multi-class semantic labels. This would facilitate the research of multi-class audio-visual segmentation.

**Comment by yyliu01** [comment]
My questions are well solved.
