### ISSUE TITLE
About Detect

### ISSUE THREAD

**Issue by CVUsers** [OpenNLPLab/AVSBench#2]
Do you have the code to actually detect any video? You only need to input a video, automatically cut 5 frames (see your reasoning needs 5 frames), and then generate its Mel map. The video cuts speech and image frames, and then sends them to the model and sends out the results. The results are visualized and mapped. This is not very difficult, nor is it a secret. Would you like to ask if you have done it? Can you share it? I have already implemented it, but it is very complicated and has no real-time performance.

**Comment by jasongief** [comment]
Hi, we have shown some demos on our [project page](https://opennlplab.github.io/AVSBench/) for video inference. During inference, the input of the AVS model should have the same shape as in model training, i.e., 5 frames and 5-seconds of audio.

You may need to densely sample the video frames (e.g., 25 FPS) to generate more segmentation masks, and then get the inference video. I am glad to hear that you have implemented this, you could have a pull request or send me an email for more discussions.

Btw, in my opinion, it is difficult to perform the audio-visual segmentation in real-time because the audio signal used in AVS model usually lasts several seconds, for example, you may need at least one second to recognize the sound.

**Comment by Klawens** [comment]
> Do you have the code to actually detect any video? You only need to input a video, automatically cut 5 frames (see your reasoning needs 5 frames), and then generate its Mel map. The video cuts speech and image frames, and then sends them to the model and sends out the results. The results are visualized and mapped. This is not very difficult, nor is it a secret. Would you like to ask if you have done it? Can you share it? I have already implemented it, but it is very complicated and has no real-time performance.

Or maybe you can share the code.😂
